[package]
name = "eric_ortega_rodriguez_mini_project_8"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.1"
serde = { version = "1.0", features = ["derive"] }
ndarray = "0.15"
ndarray_stats = "0.6.0"
