[package]
name = "Eric_Ortega_Rodriguez_Mini_Project_8"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.1.6"
ndarray = "0.15.4"
ndarray-stats = "0.4.0"
serde = { version = "1.0", features = ["derive"] }